### ISSUE TITLE
Weights Link

### ISSUE THREAD

**Issue by TharakaMadhusanka** [pavitrakumar78/Street-View-House-Numbers-SVHN-Detection-and-Classification-using-CNN#1]
Hi can u mention the link,

'Weights for both CNNs and .h5 files for train and test datasets are available in the link below:'

**Comment by pavitrakumar78** [comment]
Sorry! I forgot to include them.
Here are the links:

CNN Weights: https://drive.google.com/open?id=1vv7vzqzGjjUqjcCZYeX_NaGrqSU1Ami2  
Dataset: https://drive.google.com/open?id=1KfVqQHjimQnXdzsCtQurwmTSpMe2mmA7  

Put these in cnn_models and data folders.
