### ISSUE TITLE
Create h5 and assign labels

### ISSUE THREAD

**Issue by TharakaMadhusanka** [pavitrakumar78/Street-View-House-Numbers-SVHN-Detection-and-Classification-using-CNN#3]
Hi,

Can I know how did you assign the labels for each image ? 

And what is the use of .mat file in SVHN ?

**Comment by pavitrakumar78** [comment]
The code [construct_datasets.py](https://github.com/pavitrakumar78/Street-View-House-Numbers-SVHN-Detection-and-Classification-using-CNN/blob/master/construct_datasets.py) takes the dataset (images, mat files) and turns it into.h5 files.   
For more information about the mat files, check the[ dataset website](http://ufldl.stanford.edu/housenumbers/).

Edit: It seems you edited your question. Labels are from the mat files of the original dataset from the website linked above.

**Comment by TharakaMadhusanka** [comment]
So, here the labels for each digit is included in the .mat file ryt ? :) By extracting that, we can have the label for each bounding box digit ? this is what you followed ?

**Comment by pavitrakumar78** [comment]
Yes.
