### ISSUE TITLE
How we can use it ?

### ISSUE THREAD

**Issue by Malouke** [pavitrakumar78/Street-View-House-Numbers-SVHN-Detection-and-Classification-using-CNN#4]
Hello,
 thank you so much about shairng your poject .

can i ask you moore details about how we can use it well ?

thank for advance

**Comment by pavitrakumar78** [comment]
Not sure what you mean, but if you are asking what improvement can be made, here are some things you can do:
- Come up with better CNN architectures
- Try to use better pre-processing methods
- Improve the bounding box estimation logic
- Try using other images and custom labeled data as input  

These are just high-level ideas, but you can work on improving even small parts of each section which may improve accuracy even by a little bit.

**Comment by Malouke** [comment]
hello ,
thank you again for reply,
I mean i want test your project in personal images but i am not expert and i want realy some basics stuffs like how i can use your model to try detect numbers in my personnal pictures.

How i can launch the script ?
where i should put my images ?
do i should train the modele  or use the save weights in your google drive .... ?


thanks for adance .

**Comment by pavitrakumar78** [comment]
All the required instructions are on the readme itself. Download the full repo and put the weights and data files into the respective folders and run `combi_models.py`. 
Whether you want to train or use pre-trained models - that's up to you.

**Comment by Malouke** [comment]
ok thank 's for your reply,
i am so sorry if  my question was no clear.

my simple question it's where i should put my own images for testing ?

thank's for adavance.

**Comment by pavitrakumar78** [comment]
Anywhere you want. Read the code [here](https://github.com/pavitrakumar78/Street-View-House-Numbers-SVHN-Detection-and-Classification-using-CNN/blob/master/combi_models.py#L240). `find_box_and_predict_digit()` is what you need and it's input is a numpy array. You have to read the image and pass it to the function. Do look at how the images are processed for training and make sure you do the same processing if you want to use the pre-trained models.

**Comment by Malouke** [comment]
thank's for your help . 
i test he work well ,
i test only on my cpu i want ask you if i can use my gpu GTX 2 GB memory to play with data ?

**Comment by pavitrakumar78** [comment]
Yes, you can use your GPU.

**Comment by Malouke** [comment]
thank's again
